const batch = [
  {
    id: 1,
    name: 'Liam',
    ticket_number: 1001,
    ticket_topic: 'React Js',
    exam_grade: 10,
    rating_grade: 10,
    comments: '2022-Batch-1',
  },
  {
    id: 2,
    name: 'Noah',
    ticket_number: 1002,
    ticket_topic: 'React Js',
    exam_grade: 9,
    rating_grade: 9,
    comments: '2022-Batch-1',
  },
  {
    id: 3,
    name: 'Oliver',
    ticket_number: 1003,
    ticket_topic: 'React Js',
    exam_grade: 7,
    rating_grade: 10,
    comments: '2022-Batch-1',
  },
  {
    id: 4,
    name: 'Elijah',
    ticket_number: 1004,
    ticket_topic: 'React Js',
    exam_grade: 6,
    rating_grade: 1,
    comments: '2022-Batch-1',
  },
  {
    id: 5,
    name: 'James',
    ticket_number: 1005,
    ticket_topic: 'React Js',
    exam_grade: 4,
    rating_grade: 3,
    comments: '2022-Batch-1',
  },
  {
    id: 6,
    name: 'William',
    ticket_number: 1006,
    ticket_topic: 'React Js',
    exam_grade: 1,
    rating_grade: 1,
    comments: '2022-Batch-1',
  },
  {
    id: 7,
    name: 'Benjamin',
    ticket_number: 1007,
    ticket_topic: 'React Js',
    exam_grade: 10,
    rating_grade: 8,
    comments: '2022-Batch-1',
  },
  {
    id: 8,
    name: 'Lucas',
    ticket_number: 1008,
    ticket_topic: 'React Js',
    exam_grade: 3,
    rating_grade: 5,
    comments: '2022-Batch-1',
  },
  {
    id: 9,
    name: 'Henry',
    ticket_number: 1009,
    ticket_topic: 'React Js',
    exam_grade: 6,
    rating_grade: 7,
    comments: '2022-Batch-1',
  },
  {
    id: 10,
    name: 'Theodore',
    ticket_number: 1010,
    ticket_topic: 'React Js',
    exam_grade: 6,
    rating_grade: 10,
    comments: '2022-Batch-1',
  },
  {
    id: 11,
    name: 'Jack',
    ticket_number: 1011,
    ticket_topic: 'React Js',
    exam_grade: 2,
    rating_grade: 10,
    comments: '2022-Batch-1',
  },
  {
    id: 12,
    name: 'Levi',
    ticket_number: 1012,
    ticket_topic: 'React Js',
    exam_grade: 3,
    rating_grade: 2,
    comments: '2022-Batch-1',
  },
  {
    id: 13,
    name: 'Alexander',
    ticket_number: 1013,
    ticket_topic: 'React Js',
    exam_grade: 6,
    rating_grade: 7,
    comments: '2022-Batch-1',
  },
  {
    id: 14,
    name: 'Jackson',
    ticket_number: 1014,
    ticket_topic: 'React Js',
    exam_grade: 5,
    rating_grade: 5,
    comments: '2022-Batch-1',
  },
  {
    id: 15,
    name: 'Mateo',
    ticket_number: 1015,
    ticket_topic: 'React Js',
    exam_grade: 5,
    rating_grade: 1,
    comments: '2022-Batch-1',
  },
  {
    id: 16,
    name: 'Daniel',
    ticket_number: 1016,
    ticket_topic: 'React Js',
    exam_grade: 8,
    rating_grade: 7,
    comments: '2022-Batch-1',
  },
  {
    id: 17,
    name: 'Michael',
    ticket_number: 1017,
    ticket_topic: 'React Js',
    exam_grade: 9,
    rating_grade: 10,
    comments: '2022-Batch-1',
  },
  {
    id: 18,
    name: 'Mason',
    ticket_number: 1018,
    ticket_topic: 'React Js',
    exam_grade: 9,
    rating_grade: 7,
    comments: '2022-Batch-1',
  },
  {
    id: 19,
    name: 'Sebastian',
    ticket_number: 1019,
    ticket_topic: 'React Js',
    exam_grade: 0,
    rating_grade: 5,
    comments: '2022-Batch-1',
  },
  {
    id: 20,
    name: 'Ethan',
    ticket_number: 1020,
    ticket_topic: 'React Js',
    exam_grade: 7,
    rating_grade: 3,
    comments: '2022-Batch-1',
  },
];

export default batch;
